# Generated by Django 3.2.16 on 2023-04-09 16:14

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=200)),
                ('eventDescription', models.TextField()),
                ('eventPublished', models.DateTimeField(default=datetime.datetime(2023, 4, 9, 12, 14, 55, 624637), verbose_name='date published')),
                ('eventId', models.CharField(default=uuid.UUID('3280a362-0ea6-4b3d-be01-8112ae5b29ba'), max_length=16, null=True, unique=True)),
            ],
        ),
    ]
