# Generated by Django 3.2.16 on 2023-04-09 16:20

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventId',
            field=models.CharField(default=uuid.UUID('4e1c29c3-8fe5-40c7-9c04-b995b4612638'), max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventPublished',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 9, 12, 20, 52, 48952), verbose_name='date published'),
        ),
    ]
