# Generated by Django 3.2.16 on 2023-04-10 02:37

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230409_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityId', models.CharField(default=uuid.UUID('9ca46395-552c-4a33-8c49-b0005a5330fd'), max_length=36, null=True, unique=True)),
                ('activityStart', models.DateTimeField(default=datetime.datetime(2023, 4, 9, 22, 37, 0, 945164), verbose_name='activity start')),
                ('activityEnd', models.DateTimeField(default=datetime.datetime(2023, 4, 9, 22, 37, 0, 945164), verbose_name='activity end')),
                ('activityVolunteerId', models.CharField(default=uuid.UUID('50d9883f-47e5-4c2c-b007-0577e3b69fde'), max_length=36, null=True, unique=True)),
                ('eventId', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='LimActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityId', models.CharField(default=uuid.UUID('1e917d4c-893b-4402-9da3-fc31a9ce3225'), max_length=36, null=True, unique=True)),
                ('numberOfParticipants', models.BigIntegerField(default=0)),
                ('activityStart', models.DateTimeField(default=datetime.datetime(2023, 4, 9, 22, 37, 0, 945665), verbose_name='activity start')),
                ('activityEnd', models.DateTimeField(default=datetime.datetime(2023, 4, 9, 22, 37, 0, 945665), verbose_name='activity end')),
                ('activityVolunteerId', models.CharField(default=uuid.UUID('09cd861c-dcbe-4d31-849e-d216099566bf'), max_length=36, null=True, unique=True)),
                ('eventId', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityId', models.CharField(default=uuid.UUID('5a728332-cf7a-4593-8eba-bf4f110f7d28'), max_length=36, null=True, unique=True)),
                ('activityStart', models.DateTimeField(default=datetime.datetime(2023, 4, 9, 22, 37, 0, 945164), verbose_name='activity start')),
                ('activityEnd', models.DateTimeField(default=datetime.datetime(2023, 4, 9, 22, 37, 0, 945164), verbose_name='activity end')),
                ('activityVolunteerId', models.CharField(default=uuid.UUID('1596c625-758e-45a3-8ecc-69d163879a1b'), max_length=36, null=True, unique=True)),
                ('eventId', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleId', models.CharField(default=uuid.UUID('f09f5acd-a44c-436e-b880-f5b2622db39c'), max_length=36, null=True, unique=True)),
                ('vehicleMake', models.CharField(max_length=30)),
                ('vehicleModel', models.CharField(max_length=30)),
                ('vehicleYear', models.CharField(max_length=4)),
                ('vehicleLicensePlateState', models.CharField(max_length=14)),
                ('vehicleLicensePlateNum', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleId', models.CharField(max_length=36)),
                ('eventId', models.CharField(max_length=36)),
                ('vehicleType', models.CharField(max_length=36)),
                ('trailPass', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='eventId',
            field=models.CharField(default=uuid.UUID('2dea08e5-9411-41c5-b1bd-ff06d5cc8f27'), max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventPublished',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 9, 22, 37, 0, 944665), verbose_name='date published'),
        ),
    ]
