# Generated by Django 3.2.16 on 2023-04-10 02:51

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230409_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activityEnd',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 9, 22, 51, 3, 239096), verbose_name='activity end'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activityId',
            field=models.CharField(default=uuid.UUID('024db3de-88c8-4b68-bea8-18e23ec0732f'), max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activityStart',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 9, 22, 51, 3, 239096), verbose_name='activity start'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activityVolunteerId',
            field=models.CharField(default=uuid.UUID('09618188-e628-4ec4-847b-408e10086373'), max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventId',
            field=models.CharField(default=uuid.UUID('d68666a1-a222-471a-ae1b-fdd5966cde33'), max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventPublished',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 9, 22, 51, 3, 238596), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='limactivity',
            name='activityEnd',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 9, 22, 51, 3, 239596), verbose_name='activity end'),
        ),
        migrations.AlterField(
            model_name='limactivity',
            name='activityId',
            field=models.CharField(default=uuid.UUID('2e3017de-c25a-48b1-afc8-068ba0b2f146'), max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='limactivity',
            name='activityStart',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 9, 22, 51, 3, 239596), verbose_name='activity start'),
        ),
        migrations.AlterField(
            model_name='limactivity',
            name='activityVolunteerId',
            field=models.CharField(default=uuid.UUID('606ccda7-9595-4230-8d14-3ff7ddf120f0'), max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='trail',
            name='activityEnd',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 9, 22, 51, 3, 239096), verbose_name='activity end'),
        ),
        migrations.AlterField(
            model_name='trail',
            name='activityId',
            field=models.CharField(default=uuid.UUID('27bc562a-fec1-4a75-af87-f4959c70a215'), max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='trail',
            name='activityStart',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 9, 22, 51, 3, 239096), verbose_name='activity start'),
        ),
        migrations.AlterField(
            model_name='trail',
            name='activityVolunteerId',
            field=models.CharField(default=uuid.UUID('1abe6c26-aa30-4fae-9af8-35ec50507c7a'), max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicleId',
            field=models.CharField(default=uuid.UUID('a1c9c93a-4efa-457f-adff-f4003162f910'), max_length=36, null=True, unique=True),
        ),
    ]
