# Generated by Django 3.2.16 on 2023-04-10 22:51

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230409_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activityDescription',
            field=models.TextField(default='text'),
        ),
        migrations.AddField(
            model_name='activity',
            name='activityName',
            field=models.CharField(default='activity name', max_length=200),
        ),
        migrations.AddField(
            model_name='trail',
            name='trailName',
            field=models.CharField(default='trail name', max_length=200),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activityEnd',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 10, 18, 51, 56, 546596), verbose_name='activity end'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activityId',
            field=models.CharField(default=uuid.UUID('84a6fbad-01b5-4028-bc31-f9710c42dd36'), max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activityStart',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 10, 18, 51, 56, 546596), verbose_name='activity start'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activityVolunteerId',
            field=models.CharField(default=uuid.UUID('9c461c25-0bf3-4655-8a20-a35f9c63a464'), max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventId',
            field=models.CharField(default=uuid.UUID('a6dd71cb-0ce0-4237-94a8-b5b999654f5b'), max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventPublished',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 10, 18, 51, 56, 546596), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='limactivity',
            name='activityEnd',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 10, 18, 51, 56, 547096), verbose_name='activity end'),
        ),
        migrations.AlterField(
            model_name='limactivity',
            name='activityId',
            field=models.CharField(default=uuid.UUID('42358d59-cd56-4ff5-8c13-d286859dba2e'), max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='limactivity',
            name='activityStart',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 10, 18, 51, 56, 547096), verbose_name='activity start'),
        ),
        migrations.AlterField(
            model_name='limactivity',
            name='activityVolunteerId',
            field=models.CharField(default=uuid.UUID('538b43d4-9ce3-4bd5-9276-2b6d37d57805'), max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='trail',
            name='activityEnd',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 10, 18, 51, 56, 547096), verbose_name='activity end'),
        ),
        migrations.AlterField(
            model_name='trail',
            name='activityId',
            field=models.CharField(default=uuid.UUID('789b4b06-2743-477c-9ab3-e20bfaafc116'), max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='trail',
            name='activityStart',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 10, 18, 51, 56, 547096), verbose_name='activity start'),
        ),
        migrations.AlterField(
            model_name='trail',
            name='activityVolunteerId',
            field=models.CharField(default=uuid.UUID('65855c2b-d547-405e-be49-0aee11ed1ca3'), max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicleId',
            field=models.CharField(default=uuid.UUID('08a821db-2e07-4fc2-9e7a-f4f036c02999'), max_length=36, null=True, unique=True),
        ),
    ]
